### ISSUE TITLE
Error while running train_word_embeddings.py

### ISSUE THREAD

**Issue by SummmerSnow** [analvikingur/pytorch_RVAE#14]
File "/pytorch_RVAE-master/utils/functional.py", line 2, in fold
    return a if (len(l) == 0) else fold(f, l[1:], f(a, l[0]))
  File "/pytorch_RVAE-master/utils/functional.py", line 2, in fold
    return a if (len(l) == 0) else fold(f, l[1:], f(a, l[0]))
  File "/pytorch_RVAE-master/utils/functional.py", line 6, in f_and
    return (x and y)
RuntimeError: bool value of Tensor with more than one value is ambiguous

**Comment by berzentine** [comment]
I have a similar error, how do you fix this?

**Comment by SummmerSnow** [comment]
I fix this according to previous issue,
just need to comment out 'assert parameters_allocation_check' in neg.py as a workaround.

**Comment by SummmerSnow** [comment]
> I have a similar error, how do you fix this?

I fix this according to previous issue,
just need to comment out 'assert parameters_allocation_check' in neg.py as a workaround.
