### ISSUE TITLE
Scaling of CE loss

### ISSUE THREAD

**Issue by SeanNaren** [analvikingur/pytorch_RVAE#3]
Hey! Was wondering why the CE loss is multiplied by the value `79` [here](https://github.com/analvikingur/pytorch_RVAE/blob/master/model/rvae.py#L110). Is there any intuition behind this?

Thanks for your work :)

**Comment by kefirski** [comment]
Hi!

Here I have answered on this question

https://github.com/analvikingur/pytorch_RVAE/issues/2

**Comment by SeanNaren** [comment]
Thanks @analvikingur!

**Comment by kefirski** [comment]
You are welcome
